-- recipes 테이블의 rcp_seq 컬럼에 ID 자동 생성 기능을 추가합니다.
-- 이 컬럼은 기본 키이며, GenerationType.IDENTITY 전략을 사용하므로
-- 데이터베이스 레벨에서 값이 자동으로 생성되어야 합니다.
ALTER TABLE recipes ALTER COLUMN rcp_seq ADD GENERATED BY DEFAULT AS IDENTITY;
